### ISSUE TITLE
Nothing happens?

### ISSUE THREAD

**Issue by almereyda** [robertjlooby/confsinfo#35]
I clicked everything, but nothing happens. Blockers are disabled.

```
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36
```

![bildschirmfoto von 2016-10-28 05-28-47](https://cloud.githubusercontent.com/assets/1645308/19794008/8b031fee-9ccf-11e6-8331-b0e3ef242aaf.png)

Am I doing something wrong?

**Comment by robertjlooby** [comment]
All the filters are exclusive. If you just `Reset` do you see the list of conferences on the bottom?

**Comment by almereyda** [comment]
Oh, sorry, yes. That wasn't obvious.
I think a line like *0 conferences matched your criteria.* down there could be really helpful.
